// The Text panel's font picker: every family set in its own face, grouped,
// searchable, with uploading at the foot of the list.
//
// Bundled families are drawn from pre-laid-out outlines
// (`lib/text/fontPreviews.ts`, generated by scripts/gen-font-previews.ts), so
// opening the list costs a few KB instead of fetching every font. An uploaded
// font is already in this browser, so its name is laid out live.

import { useEffect, useLayoutEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react'
import { createPortal } from 'react-dom'
import {
  allFonts,
  FONT_ACCEPT,
  fontsVersion,
  loadedFace,
  loadFont,
  lookupFace,
  subscribeFonts,
  type FontCategory,
  type FontEntry,
} from '../../lib/text/fonts'
import type { FontPreview } from '../../lib/text/fontPreviews'
import { layoutText } from '../../lib/text/layout'
import { newTextData, replaceText } from '../../lib/text/edit'
import { subPathsToD } from '../../lib/path/model'
import { subPathsTightBounds } from '../../lib/path/geometry'
import { Check, ChevronDown, Search, Upload } from '../ui/icons'
import { TipLabel, Tooltip } from '../ui/Tooltip'

const CATEGORY: Record<FontCategory, string> = {
  sans: 'Sans serif',
  serif: 'Serif',
  display: 'Display',
  script: 'Script',
  mono: 'Monospace',
  yours: 'Your fonts',
}
const ORDER: FontCategory[] = ['sans', 'serif', 'display', 'script', 'mono', 'yours']

const MENU_W = 288
const MENU_MAX_H = 380

// Loaded once, by the first picker that mounts; small, but no reason to put it
// in the editor's chunk for people who never type.
let previews: Record<string, FontPreview> | null = null
let previewsLoading: Promise<void> | null = null
function usePreviews(): Record<string, FontPreview> | null {
  const [, bump] = useState(0)
  useEffect(() => {
    if (previews) return
    previewsLoading ??= import('../../lib/text/fontPreviews').then((m) => {
      previews = m.FONT_PREVIEWS
    })
    let alive = true
    void previewsLoading.then(() => alive && bump((n) => n + 1))
    return () => {
      alive = false
    }
  }, [])
  return previews
}

/** An uploaded font's name, laid out in itself (null until its face is loaded). */
function livePreview(f: FontEntry): FontPreview | null {
  const face = loadedFace(f.id, false)
  if (!face) return null
  const data = replaceText(newTextData({ x: 0, y: 0 }, 100, { font: f.id }), 0, 0, f.family)
  const subs = layoutText(data, lookupFace, String).children.flatMap((c) => c.subPaths)
  const box = subPathsTightBounds(subs)
  const ascent = (face.ascender / face.upem) * 100
  return {
    d: subPathsToD(subs, 0),
    w: Math.ceil(box ? box.x + box.w : 0),
    h: Math.ceil(ascent - (face.descender / face.upem) * 100),
    ascent,
    axes: face.axes.map((a) => `${a.tag} ${a.min}–${a.max}`),
    italic: false,
  }
}

function Specimen({ p, height, fallback }: { p: FontPreview | null; height: number; fallback: string }) {
  if (!p || !p.d) return <span className="truncate">{fallback}</span>
  return (
    <svg
      viewBox={`0 ${-p.ascent} ${Math.max(1, p.w)} ${p.h}`}
      height={height}
      width={(Math.max(1, p.w) / p.h) * height}
      className="block max-w-full shrink-0"
      aria-hidden
    >
      <path d={p.d} fill="currentColor" />
    </svg>
  )
}

export function FontPicker({
  value,
  onPick,
  onUpload,
}: {
  /** The font id, or undefined when the selection mixes fonts. */
  value: string | undefined
  onPick: (id: string) => void
  /** Add a font file; resolves to an error message, or null when it was added. */
  onUpload: (file: File) => Promise<string | null>
}) {
  useSyncExternalStore(subscribeFonts, fontsVersion)
  const bundled = usePreviews()
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [cursor, setCursor] = useState(0)
  const [pos, setPos] = useState<{ left: number; top: number; maxH: number } | null>(null)
  const [error, setError] = useState<string | null>(null)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const menuRef = useRef<HTMLDivElement>(null)
  const searchRef = useRef<HTMLInputElement>(null)
  const fileRef = useRef<HTMLInputElement>(null)

  const fonts = allFonts()
  const preview = (f: FontEntry) => (f.uploaded ? livePreview(f) : (bundled?.[f.id] ?? null))

  // Ordered by category, filtered by the search, as one flat list for the keys.
  const list = useMemo(() => {
    const q = query.trim().toLowerCase()
    return ORDER.flatMap((c) => fonts.filter((f) => f.category === c && (!q || f.family.toLowerCase().includes(q))))
  }, [fonts, query])

  // Uploaded faces live in IndexedDB: load them so their rows can draw.
  useEffect(() => {
    if (!open) return
    for (const f of fonts) if (f.uploaded) void loadFont(f.id)
  }, [open, fonts])

  // Read on open only: the cursor starts on the current font.
  const startRef = useRef(0)
  startRef.current = Math.max(
    0,
    list.findIndex((f) => f.id === value),
  )
  useLayoutEffect(() => {
    if (!open) return
    const b = triggerRef.current?.getBoundingClientRect()
    if (!b) return
    const w = Math.max(MENU_W, b.width)
    const below = window.innerHeight - b.bottom - 12
    const above = b.top - 12
    // Below unless there is clearly more room above (a trigger low on a phone).
    const down = below >= Math.min(MENU_MAX_H, 240) || below >= above
    const maxH = Math.min(MENU_MAX_H, down ? below : above)
    setPos({
      left: Math.max(8, Math.min(b.left, window.innerWidth - w - 8)),
      top: down ? b.bottom + 6 : b.top - 6 - maxH,
      maxH,
    })
    setQuery('')
    setError(null)
    setCursor(startRef.current)
  }, [open])

  useEffect(() => {
    if (!open) return
    const onDown = (e: PointerEvent) => {
      const t = e.target as Node
      if (!menuRef.current?.contains(t) && !triggerRef.current?.contains(t)) setOpen(false)
    }
    const close = () => setOpen(false)
    window.addEventListener('pointerdown', onDown, true)
    window.addEventListener('resize', close)
    return () => {
      window.removeEventListener('pointerdown', onDown, true)
      window.removeEventListener('resize', close)
    }
  }, [open])

  // Focus the search once the popover exists (it mounts after `pos` is set).
  useEffect(() => {
    if (open && pos) searchRef.current?.focus({ preventScroll: true })
  }, [open, pos])

  // Keep the keyboard row in view.
  useEffect(() => {
    if (!open) return
    menuRef.current?.querySelector(`[data-font-row="${cursor}"]`)?.scrollIntoView({ block: 'nearest' })
  }, [cursor, open])

  const pick = (id: string) => {
    setOpen(false)
    triggerRef.current?.focus()
    onPick(id)
  }

  const onKeyDown = (e: React.KeyboardEvent) => {
    const n = list.length
    if (e.key === 'ArrowDown' && n) setCursor((c) => (c + 1) % n)
    else if (e.key === 'ArrowUp' && n) setCursor((c) => (c - 1 + n) % n)
    else if (e.key === 'Enter' && list[cursor]) pick(list[cursor].id)
    else if (e.key === 'Escape') {
      setOpen(false)
      triggerRef.current?.focus()
    } else if (e.key === 'Tab') setOpen(false)
    else return
    e.preventDefault()
    // The rail's own keys (and the studio's shortcuts) must not see these.
    e.stopPropagation()
  }

  const current = value ? fonts.find((f) => f.id === value) : undefined

  return (
    <>
      <Tooltip label={open ? '' : <TipLabel title="Font" detail="Bundled open-source fonts, plus any you upload." />}>
        <button
          ref={triggerRef}
          type="button"
          aria-label={`Font: ${current?.family ?? 'mixed'}`}
          aria-haspopup="listbox"
          aria-expanded={open}
          onClick={() => setOpen((o) => !o)}
          className="input flex h-8 min-w-0 flex-1 items-center gap-1.5 text-left text-xs"
        >
          <span className="flex min-w-0 flex-1 items-center overflow-hidden text-ink">
            {current ? (
              <Specimen p={preview(current)} height={15} fallback={current.family} />
            ) : (
              <span className="text-muted">Mixed fonts</span>
            )}
          </span>
          <ChevronDown size={13} className="shrink-0 text-muted" />
        </button>
      </Tooltip>

      {open &&
        pos &&
        createPortal(
          <div
            ref={menuRef}
            role="dialog"
            aria-label="Choose a font"
            onKeyDown={onKeyDown}
            className="fixed z-[55] flex flex-col overflow-hidden rounded-xl border border-line bg-surface shadow-lg"
            style={{
              left: pos.left,
              top: pos.top,
              width: Math.max(MENU_W, triggerRef.current?.offsetWidth ?? 0),
              maxHeight: pos.maxH,
            }}
          >
            <label className="flex items-center gap-1.5 border-b border-line px-2.5 py-2">
              <Search size={13} className="shrink-0 text-faint" />
              <input
                ref={searchRef}
                value={query}
                onChange={(e) => {
                  setQuery(e.target.value)
                  setCursor(0)
                }}
                placeholder="Search fonts"
                aria-label="Search fonts"
                role="combobox"
                aria-expanded
                aria-controls="font-listbox"
                aria-activedescendant={list[cursor] ? `font-opt-${cursor}` : undefined}
                className="min-w-0 flex-1 bg-transparent text-xs text-ink outline-none placeholder:text-faint"
              />
            </label>

            <div id="font-listbox" role="listbox" aria-label="Fonts" className="min-h-0 flex-1 overflow-y-auto p-1">
              {list.length === 0 && (
                <p className="px-2 py-3 text-center text-xs text-faint">No font matches “{query}”.</p>
              )}
              {ORDER.map((c) => {
                const rows = list.map((f, i) => ({ f, i })).filter(({ f }) => f.category === c)
                if (rows.length === 0) return null
                return (
                  // biome-ignore lint/a11y/useSemanticElements: an ARIA group inside a listbox, not a form fieldset
                  <div key={c} role="group" aria-label={CATEGORY[c]}>
                    <div className="px-2 pt-2 pb-1 text-[0.62rem] font-semibold tracking-wide text-faint uppercase">
                      {CATEGORY[c]}
                    </div>
                    {rows.map(({ f, i }) => {
                      const p = preview(f)
                      const selected = f.id === value
                      const variable = p?.axes.some((a) => a.startsWith('wght')) ?? false
                      return (
                        // biome-ignore lint/a11y/useKeyWithClickEvents: the keys live on the search combobox (aria-activedescendant)
                        <div
                          key={f.id}
                          id={`font-opt-${i}`}
                          data-font-row={i}
                          role="option"
                          aria-selected={selected}
                          aria-label={f.family}
                          tabIndex={-1}
                          onClick={() => pick(f.id)}
                          onPointerEnter={() => setCursor(i)}
                          className={`flex cursor-pointer items-center gap-2 rounded-lg px-2 py-1.5 ${
                            i === cursor ? 'bg-surface-3' : ''
                          } ${selected ? 'text-accent' : 'text-ink'}`}
                        >
                          <span className="flex h-6 min-w-0 flex-1 items-center overflow-hidden">
                            <Specimen p={p} height={20} fallback={f.family} />
                          </span>
                          <span className="flex shrink-0 items-center gap-1 text-[0.6rem] text-faint">
                            {variable && <span className="rounded border border-line px-1">Variable</span>}
                            {p?.italic && <span className="rounded border border-line px-1 italic">Italic</span>}
                          </span>
                          <Check size={13} className={`shrink-0 ${selected ? '' : 'invisible'}`} />
                        </div>
                      )
                    })}
                  </div>
                )
              })}
            </div>

            <div className="border-t border-line p-1">
              <button
                type="button"
                onClick={() => fileRef.current?.click()}
                className="flex w-full items-center gap-2 rounded-lg px-2 py-1.5 text-left text-xs text-ink-2 hover:bg-surface-3 hover:text-ink"
              >
                <Upload size={13} className="shrink-0" />
                <span className="min-w-0 flex-1">
                  <span className="block">Upload a font…</span>
                  <span className="block text-[0.62rem] leading-tight text-faint">
                    .ttf, .otf or .woff, saved in this browser under Your fonts
                  </span>
                </span>
              </button>
              {error && <p className="px-2 pb-1 text-[0.65rem] text-red-600 dark:text-red-400">{error}</p>}
              <input
                ref={fileRef}
                type="file"
                accept={FONT_ACCEPT}
                className="hidden"
                onChange={async (e) => {
                  const file = e.target.files?.[0]
                  e.target.value = ''
                  if (!file) return
                  const err = await onUpload(file)
                  if (err) setError(err)
                  else setOpen(false)
                }}
              />
            </div>
          </div>,
          document.body,
        )}
    </>
  )
}
