// Build-time generator for the vectorize control info-dialog previews.
//
//   node src/devtest/genControlPreviews.ts      # or: npm run gen:previews
//
// Runs the REAL trace engine (traceImage) — the same code the app ships — over a
// few bundled examples, once per control variant (Smoothing None/Medium/High,
// Gradients Off/On, …), and writes the rendered SVGs into
// src/components/vectorize/controlPreviews.generated.ts. Because it imports the
// production pipeline rather than reimplementing it, the previews cannot drift
// from the engine; wiring this into `npm run build` keeps the committed file
// fresh in every release. Crisp-only — Potrace needs WASM/DOMParser the headless
// path lacks, so Engine is marked liveOnly and skipped here (compared live in the
// browser instead).

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { ensureImageData, loadPng } from './nodeHarness.ts'
import { traceImage, DEFAULT_VECTORIZE_OPTIONS } from '../lib/trace/index.ts'
import { serializeDoc, docStats } from '../lib/path/model.ts'
import { rasterizeDoc } from '../lib/render/raster.ts'
import { CONTROL_DOCS, type ExampleKey, type ExampleSource } from '../components/vectorize/controlDocs.ts'
import { SCENES } from './previewScenes.ts'

ensureImageData()

type Img = { width: number; height: number; data: Uint8ClampedArray }

/** Cap the longest side so traces stay fast and the emitted SVGs stay small. */
const MAX_DIM = 384

/** Simple box-average downscale (keeps anti-aliasing readable in the previews). */
function downscale(img: Img, maxDim: number): Img {
  const { width, height } = img
  const scale = Math.min(1, maxDim / Math.max(width, height))
  if (scale >= 1) return img
  const w = Math.max(1, Math.round(width * scale))
  const h = Math.max(1, Math.round(height * scale))
  const out = new Uint8ClampedArray(w * h * 4)
  const sx = width / w
  const sy = height / h
  for (let y = 0; y < h; y++) {
    const y0 = Math.floor(y * sy)
    const y1 = Math.max(y0 + 1, Math.min(height, Math.floor((y + 1) * sy)))
    for (let x = 0; x < w; x++) {
      const x0 = Math.floor(x * sx)
      const x1 = Math.max(x0 + 1, Math.min(width, Math.floor((x + 1) * sx)))
      let r = 0, g = 0, b = 0, a = 0, n = 0
      for (let yy = y0; yy < y1; yy++) {
        for (let xx = x0; xx < x1; xx++) {
          const i = (yy * width + xx) * 4
          r += img.data[i]
          g += img.data[i + 1]
          b += img.data[i + 2]
          a += img.data[i + 3]
          n++
        }
      }
      const o = (y * w + x) * 4
      out[o] = r / n
      out[o + 1] = g / n
      out[o + 2] = b / n
      out[o + 3] = a / n
    }
  }
  return { width: w, height: h, data: out }
}

const bundledCache = new Map<ExampleKey, Img>()
function loadBundled(key: ExampleKey): Img {
  const cached = bundledCache.get(key)
  if (cached) return cached
  const small = downscale(loadPng(`public/examples/${key}.png`), MAX_DIM)
  bundledCache.set(key, small)
  return small
}

/** Resolve a control's example into source pixels + (for synthetic) an SVG of
 *  the source to show as the dialog's "input" thumbnail. */
function resolveExample(example: ExampleSource): { img: Img; inputSvg?: string } {
  if (example.kind === 'bundled') return { img: loadBundled(example.key) }
  const scene = SCENES[example.scene]()
  const data = rasterizeDoc(scene.doc, scene.width, scene.height)
  return {
    img: { width: scene.width, height: scene.height, data },
    inputSvg: serializeDoc(scene.doc),
  }
}

interface PreviewVariant {
  label: string
  svg: string
  paths: number
  nodes: number
}

interface ControlPreview {
  /** SVG of the synthetic source (omitted for bundled examples). */
  inputSvg?: string
  variants: PreviewVariant[]
}

const manifest: Record<string, ControlPreview> = {}

for (const doc of CONTROL_DOCS) {
  if (doc.liveOnly) continue
  const { img, inputSvg } = resolveExample(doc.example)
  const base = { ...DEFAULT_VECTORIZE_OPTIONS, engine: 'crisp' as const, ...doc.baseOpts }
  const variants: PreviewVariant[] = []
  for (const v of doc.variants) {
    const traced = await traceImage(img as unknown as ImageData, { ...base, ...v.patch })
    const stats = docStats(traced)
    variants.push({ label: v.label, svg: serializeDoc(traced), paths: stats.paths, nodes: stats.nodes })
  }
  manifest[doc.id] = { ...(inputSvg ? { inputSvg } : {}), variants }
  console.log(
    `  ${doc.id.padEnd(14)} ${variants.map((v) => `${v.label}=${v.paths}p/${v.nodes}n`).join('  ')}`,
  )
}

const header =
  '// AUTO-GENERATED by src/devtest/genControlPreviews.ts — do not edit by hand.\n' +
  '// Regenerate with `npm run gen:previews` (runs automatically on `npm run build`).\n\n'
const body =
  'export interface PreviewVariant {\n' +
  '  label: string\n' +
  '  /** Self-contained <svg> string (includes its own viewBox). */\n' +
  '  svg: string\n' +
  '  paths: number\n' +
  '  nodes: number\n' +
  '}\n\n' +
  'export interface ControlPreview {\n' +
  '  /** SVG of the synthetic source (omitted for bundled examples). */\n' +
  '  inputSvg?: string\n' +
  '  variants: PreviewVariant[]\n' +
  '}\n\n' +
  'export const CONTROL_PREVIEWS: Record<string, ControlPreview> = ' +
  JSON.stringify(manifest, null, 2) +
  '\n'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const target = join(root, 'src', 'components', 'vectorize', 'controlPreviews.generated.ts')
writeFileSync(target, header + body)
console.log(`\nwrote ${target}`)
