// GENERATED by scripts/port-motion-icons.mjs — do not edit; re-run the script.
// Import icons from HERE, not from lucide-react: an icon listed below animates
// when its control is hovered; every other lucide icon passes through static.

export * from 'lucide-react'
import {
  ArrowLeft as ArrowLeftStatic,
  ArrowRight as ArrowRightStatic,
  Bot as BotStatic,
  Box as BoxStatic,
  Brush as BrushStatic,
  Check as CheckStatic,
  CheckCheck as CheckCheckStatic,
  ChevronDown as ChevronDownStatic,
  ChevronLeft as ChevronLeftStatic,
  ChevronRight as ChevronRightStatic,
  CircleHelp as CircleHelpStatic,
  Code as CodeStatic,
  Coffee as CoffeeStatic,
  Contrast as ContrastStatic,
  Copy as CopyStatic,
  Download as DownloadStatic,
  Expand as ExpandStatic,
  ExternalLink as ExternalLinkStatic,
  Eye as EyeStatic,
  EyeOff as EyeOffStatic,
  Feather as FeatherStatic,
  Folder as FolderStatic,
  Frame as FrameStatic,
  GripVertical as GripVerticalStatic,
  Group as GroupStatic,
  Hand as HandStatic,
  Heart as HeartStatic,
  History as HistoryStatic,
  Layers as LayersStatic,
  LayoutGrid as LayoutGridStatic,
  Lightbulb as LightbulbStatic,
  Link2 as Link2Static,
  Lock as LockStatic,
  MapPin as MapPinStatic,
  Maximize2 as Maximize2Static,
  Menu as MenuStatic,
  Moon as MoonStatic,
  PenTool as PenToolStatic,
  Play as PlayStatic,
  Plus as PlusStatic,
  Redo as RedoStatic,
  RefreshCw as RefreshCwStatic,
  RotateCcw as RotateCcwStatic,
  RotateCw as RotateCwStatic,
  Scissors as ScissorsStatic,
  Search as SearchStatic,
  Shrink as ShrinkStatic,
  SlidersHorizontal as SlidersHorizontalStatic,
  Sparkles as SparklesStatic,
  Star as StarStatic,
  Sun as SunStatic,
  Terminal as TerminalStatic,
  Timer as TimerStatic,
  ToggleLeft as ToggleLeftStatic,
  ToggleRight as ToggleRightStatic,
  Trash2 as Trash2Static,
  Undo as UndoStatic,
  Upload as UploadStatic,
  WandSparkles as WandSparklesStatic,
  X as XStatic,
} from 'lucide-react'
import { animated } from './AnimatedIcon'
import * as data from './motionData'

export const ArrowLeft = /* @__PURE__ */ animated(ArrowLeftStatic, data.ArrowLeft)
export const ArrowRight = /* @__PURE__ */ animated(ArrowRightStatic, data.ArrowRight)
export const Bot = /* @__PURE__ */ animated(BotStatic, data.Bot)
export const Box = /* @__PURE__ */ animated(BoxStatic, data.Box)
export const Brush = /* @__PURE__ */ animated(BrushStatic, data.Brush)
export const Check = /* @__PURE__ */ animated(CheckStatic, data.Check)
export const CheckCheck = /* @__PURE__ */ animated(CheckCheckStatic, data.CheckCheck)
export const ChevronDown = /* @__PURE__ */ animated(ChevronDownStatic, data.ChevronDown)
export const ChevronLeft = /* @__PURE__ */ animated(ChevronLeftStatic, data.ChevronLeft)
export const ChevronRight = /* @__PURE__ */ animated(ChevronRightStatic, data.ChevronRight)
export const CircleHelp = /* @__PURE__ */ animated(CircleHelpStatic, data.CircleHelp)
export const Code = /* @__PURE__ */ animated(CodeStatic, data.Code)
export const Coffee = /* @__PURE__ */ animated(CoffeeStatic, data.Coffee)
export const Contrast = /* @__PURE__ */ animated(ContrastStatic, data.Contrast)
export const Copy = /* @__PURE__ */ animated(CopyStatic, data.Copy)
export const Download = /* @__PURE__ */ animated(DownloadStatic, data.Download)
export const Expand = /* @__PURE__ */ animated(ExpandStatic, data.Expand)
export const ExternalLink = /* @__PURE__ */ animated(ExternalLinkStatic, data.ExternalLink)
export const Eye = /* @__PURE__ */ animated(EyeStatic, data.Eye)
export const EyeOff = /* @__PURE__ */ animated(EyeOffStatic, data.EyeOff)
export const Feather = /* @__PURE__ */ animated(FeatherStatic, data.Feather)
export const Folder = /* @__PURE__ */ animated(FolderStatic, data.Folder)
export const Frame = /* @__PURE__ */ animated(FrameStatic, data.Frame)
export const GripVertical = /* @__PURE__ */ animated(GripVerticalStatic, data.GripVertical)
export const Group = /* @__PURE__ */ animated(GroupStatic, data.Group)
export const Hand = /* @__PURE__ */ animated(HandStatic, data.Hand)
export const Heart = /* @__PURE__ */ animated(HeartStatic, data.Heart)
export const History = /* @__PURE__ */ animated(HistoryStatic, data.History)
export const Layers = /* @__PURE__ */ animated(LayersStatic, data.Layers)
export const LayoutGrid = /* @__PURE__ */ animated(LayoutGridStatic, data.LayoutGrid)
export const Lightbulb = /* @__PURE__ */ animated(LightbulbStatic, data.Lightbulb)
export const Link2 = /* @__PURE__ */ animated(Link2Static, data.Link2)
export const Lock = /* @__PURE__ */ animated(LockStatic, data.Lock)
export const MapPin = /* @__PURE__ */ animated(MapPinStatic, data.MapPin)
export const Maximize2 = /* @__PURE__ */ animated(Maximize2Static, data.Maximize2)
export const Menu = /* @__PURE__ */ animated(MenuStatic, data.Menu)
export const Moon = /* @__PURE__ */ animated(MoonStatic, data.Moon)
export const PenTool = /* @__PURE__ */ animated(PenToolStatic, data.PenTool)
export const Play = /* @__PURE__ */ animated(PlayStatic, data.Play)
export const Plus = /* @__PURE__ */ animated(PlusStatic, data.Plus)
export const Redo = /* @__PURE__ */ animated(RedoStatic, data.Redo)
export const RefreshCw = /* @__PURE__ */ animated(RefreshCwStatic, data.RefreshCw)
export const RotateCcw = /* @__PURE__ */ animated(RotateCcwStatic, data.RotateCcw)
export const RotateCw = /* @__PURE__ */ animated(RotateCwStatic, data.RotateCw)
export const Scissors = /* @__PURE__ */ animated(ScissorsStatic, data.Scissors)
export const Search = /* @__PURE__ */ animated(SearchStatic, data.Search)
export const Shrink = /* @__PURE__ */ animated(ShrinkStatic, data.Shrink)
export const SlidersHorizontal = /* @__PURE__ */ animated(SlidersHorizontalStatic, data.SlidersHorizontal)
export const Sparkles = /* @__PURE__ */ animated(SparklesStatic, data.Sparkles)
export const Star = /* @__PURE__ */ animated(StarStatic, data.Star)
export const Sun = /* @__PURE__ */ animated(SunStatic, data.Sun)
export const Terminal = /* @__PURE__ */ animated(TerminalStatic, data.Terminal)
export const Timer = /* @__PURE__ */ animated(TimerStatic, data.Timer)
export const ToggleLeft = /* @__PURE__ */ animated(ToggleLeftStatic, data.ToggleLeft)
export const ToggleRight = /* @__PURE__ */ animated(ToggleRightStatic, data.ToggleRight)
export const Trash2 = /* @__PURE__ */ animated(Trash2Static, data.Trash2)
export const Undo = /* @__PURE__ */ animated(UndoStatic, data.Undo)
export const Upload = /* @__PURE__ */ animated(UploadStatic, data.Upload)
export const WandSparkles = /* @__PURE__ */ animated(WandSparklesStatic, data.WandSparkles)
export const X = /* @__PURE__ */ animated(XStatic, data.X)
