// GENERATED by scripts/port-motion-icons.mjs — do not edit; re-run the script.
// Source: https://github.com/respeak-io/lucide-motion-vue @ bcdcb0b
// Geometry: Lucide (ISC). Motion: animate-ui (MIT + Commons Clause) and
// lucide-motion-vue hand-written (MIT) — the comment on each icon says which.

import type { MotionIconData } from './motionTypes'

/** arrow-left (animate-ui) */
export const ArrowLeft: MotionIconData = {
  name: "arrow-left",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M19 12H5",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "m12 19-7-7 7-7",
          },
          key: "path2",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        x: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.3,
        },
      },
      animate: {
        x: "-25%",
        transition: {
          ease: "easeInOut",
          duration: 0.3,
        },
      },
    },
    path1: {},
    path2: {},
  },
}

/** arrow-right (animate-ui) */
export const ArrowRight: MotionIconData = {
  name: "arrow-right",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M5 12h14",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "m12 5 7 7-7 7",
          },
          key: "path2",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        x: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.3,
        },
      },
      animate: {
        x: "25%",
        transition: {
          ease: "easeInOut",
          duration: 0.3,
        },
      },
    },
    path1: {},
    path2: {},
  },
}

/** bot (hand-written) */
export const Bot: MotionIconData = {
  name: "bot",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M12 8V4H8",
      },
      key: "path1",
    },
    {
      tag: "rect",
      attrs: {
        width: 16,
        height: 12,
        x: 4,
        y: 8,
        rx: 2,
      },
      key: "rect",
    },
    {
      tag: "path",
      attrs: {
        d: "M2 14h2",
      },
      key: "path2",
    },
    {
      tag: "path",
      attrs: {
        d: "M20 14h2",
      },
      key: "path3",
    },
    {
      tag: "path",
      attrs: {
        d: "M15 13v2",
      },
      key: "path4",
    },
    {
      tag: "path",
      attrs: {
        d: "M9 13v2",
      },
      key: "path5",
    },
  ],
  variants: {
    path1: {},
    rect: {},
    path2: {},
    path3: {},
    path4: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: "easeInOut",
          duration: 1.3,
        },
      },
    },
    path5: {
      initial: {
        x: 0,
        y: 0,
      },
      animate: {
        x: [0, -1.5, 1.5, 0],
        y: [0, 1.5, 1.5, 0],
        transition: {
          ease: "easeInOut",
          duration: 1.3,
        },
      },
    },
  },
}

/** box (animate-ui) */
export const Box: MotionIconData = {
  name: "box",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z",
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "m3.3 7 8.7 5 8.7-5",
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "M12 22V12",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        opacity: 1,
        pathLength: 1,
        transition: {
          duration: 0.3,
          opacity: {
            duration: 0.1,
          },
        },
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.4,
          opacity: {
            duration: 0.1,
          },
        },
      },
    },
  },
}

/** brush (animate-ui) */
export const Brush: MotionIconData = {
  name: "brush",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "m11 10 3 3",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M6.5 21A3.5 3.5 0 1 0 3 17.5a2.62 2.62 0 0 1-.708 1.792A1 1 0 0 0 3 21z",
          },
          key: "path2",
        },
        {
          tag: "path",
          attrs: {
            d: "M9.969 17.031 21.378 5.624a1 1 0 0 0-3.002-3.002L6.967 14.031",
          },
          key: "path3",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
      animate: {
        rotate: [0, -6, 6, 0],
        transformOrigin: "top right",
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
  },
}

/** check (animate-ui) */
export const Check: MotionIconData = {
  name: "check",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m4 12 5 5L20 6",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        pathLength: 1,
        opacity: 1,
        scale: 1,
      },
      animate: {
        pathLength: [0, 1],
        opacity: [0, 1],
        scale: [1, 1.1, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** check-check (animate-ui) */
export const CheckCheck: MotionIconData = {
  name: "check-check",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "m2 12 5 5L18 6",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "m13 16 1.5 1.5L22 10",
          },
          key: "path2",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 1.1, 1],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
        },
      },
    },
    path1: {
      initial: {
        pathLength: 1,
        opacity: 1,
      },
      animate: {
        pathLength: [0, 1],
        opacity: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path2: {
      initial: {
        pathLength: 1,
        opacity: 1,
      },
      animate: {
        pathLength: [0, 1],
        opacity: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.2,
        },
      },
    },
  },
}

/** chevron-down (animate-ui) */
export const ChevronDown: MotionIconData = {
  name: "chevron-down",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m6 9 6 6 6-6",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        y: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 4,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** chevron-left (animate-ui) */
export const ChevronLeft: MotionIconData = {
  name: "chevron-left",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m15 18-6-6 6-6",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        x: -4,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** chevron-right (animate-ui) */
export const ChevronRight: MotionIconData = {
  name: "chevron-right",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m9 18 6-6-6-6",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        x: 4,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** circle-help (animate-ui) */
export const CircleHelp: MotionIconData = {
  name: "circle-help",
  elements: [
    {
      tag: "circle",
      attrs: {
        cx: "12",
        cy: "12",
        r: "10",
      },
    },
    {
      tag: "g",
      attrs: {
        transition: {
          duration: 0.5,
          ease: "easeInOut",
        },
      },
      key: "variants",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M12 17h.01",
          },
        },
      ],
    },
  ],
  variants: {
    variants: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, -10, 10, -10, 0],
      },
    },
  },
}

/** code (hand-written) */
export const Code: MotionIconData = {
  name: "code",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m16 18 6-6-6-6",
      },
      key: "right",
    },
    {
      tag: "path",
      attrs: {
        d: "m8 6-6 6 6 6",
      },
      key: "left",
    },
  ],
  variants: {
    right: {
      initial: {
        x: 0,
        pathLength: 1,
      },
      animate: {
        x: [0, 3, -0.6, 0],
        pathLength: [0.2, 1],
        transition: {
          duration: 0.7,
          ease: "easeOut",
        },
      },
    },
    left: {
      initial: {
        x: 0,
        pathLength: 1,
      },
      animate: {
        x: [0, -3, 0.6, 0],
        pathLength: [0.2, 1],
        transition: {
          duration: 0.82,
          delay: 0.06,
          ease: "easeOut",
        },
      },
    },
  },
}

/** coffee (animate-ui) */
export const Coffee: MotionIconData = {
  name: "coffee",
  elements: [
    {
      tag: "path",
      attrs: {
        custom: 0.2,
        d: "M10 2v2",
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        custom: 0.4,
        d: "M14 2v2",
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        custom: 0,
        d: "M6 2v2",
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1",
      },
    },
  ],
  variants: {
    path: {
      initial: {
        y: 0,
        opacity: 1,
      },
      animate: (custom: any) => ({
    y: -3,
    opacity: [0, 1, 0],
    transition: {
      repeat: Number.POSITIVE_INFINITY,
      duration: 1.5,
      ease: "easeInOut",
      delay: 0.2 * custom,
    },
  }),
    },
  },
}

/** contrast (animate-ui) */
export const Contrast: MotionIconData = {
  name: "contrast",
  elements: [
    {
      tag: "circle",
      attrs: {
        cx: 12,
        cy: 12,
        r: 10,
      },
      key: "circle",
    },
    {
      tag: "path",
      attrs: {
        d: "M12 18a6 6 0 0 0 0-12v12z",
      },
      key: "path",
    },
  ],
  variants: {
    circle: {},
    path: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: 180,
        transformOrigin: "left center",
        transition: {
          type: "spring",
          stiffness: 80,
          damping: 10,
        },
      },
    },
  },
}

/** copy (animate-ui) */
export const Copy: MotionIconData = {
  name: "copy",
  elements: [
    {
      tag: "rect",
      attrs: {
        width: 14,
        height: 14,
        x: 8,
        y: 8,
        rx: 2,
        ry: 2,
      },
      key: "rect",
    },
    {
      tag: "path",
      attrs: {
        d: "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2",
      },
      key: "path",
    },
  ],
  variants: {
    rect: {
      initial: {
        y: 0,
        x: 0,
      },
      animate: {
        y: -3,
        x: -3,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path: {
      initial: {
        y: 0,
        x: 0,
      },
      animate: {
        y: 3,
        x: 3,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** download (animate-ui) */
export const Download: MotionIconData = {
  name: "download",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M12 15V3",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "m7 10 5 5 5-5",
          },
          key: "path2",
        },
      ],
    },
    {
      tag: "path",
      attrs: {
        d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
      },
      key: "path3",
    },
  ],
  variants: {
    group: {
      initial: {
        y: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
  },
}

/** expand (animate-ui) */
export const Expand: MotionIconData = {
  name: "expand",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group1",
      children: [
        {
          tag: "path",
          attrs: {
            d: "m15 15 6 6",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M21 16v5h-5",
          },
          key: "path3",
        },
      ],
    },
    {
      tag: "g",
      attrs: {},
      key: "group2",
      children: [
        {
          tag: "path",
          attrs: {
            d: "m15 9 6-6",
          },
          key: "path2",
        },
        {
          tag: "path",
          attrs: {
            d: "M21 8V3h-5",
          },
          key: "path4",
        },
      ],
    },
    {
      tag: "g",
      attrs: {},
      key: "group3",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 16v5h5",
          },
          key: "path5",
        },
        {
          tag: "path",
          attrs: {
            d: "m3 21 6-6",
          },
          key: "path6",
        },
      ],
    },
    {
      tag: "g",
      attrs: {},
      key: "group4",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 8V3h5",
          },
          key: "path7",
        },
        {
          tag: "path",
          attrs: {
            d: "M9 9 3 3",
          },
          key: "path8",
        },
      ],
    },
  ],
  variants: {
    group1: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 2,
        x: 2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    group2: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: -2,
        x: 2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    group3: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 2,
        x: -2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    group4: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: -2,
        x: -2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
    path4: {},
    path5: {},
    path6: {},
    path7: {},
    path8: {},
  },
}

/** external-link (animate-ui) */
export const ExternalLink: MotionIconData = {
  name: "external-link",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M15 3h6v6",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M10 14 21 3",
          },
          key: "path2",
        },
      ],
    },
    {
      tag: "path",
      attrs: {
        d: "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6",
      },
      key: "path3",
    },
  ],
  variants: {
    group: {
      initial: {
        x: 0,
        y: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        x: 2,
        y: -2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
  },
}

/** eye (animate-ui) */
export const Eye: MotionIconData = {
  name: "eye",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
        style: {
          originY: "50%",
        },
        transition: {
          duration: 0.4,
          ease: "easeInOut",
        },
      },
      key: "path",
    },
    {
      tag: "circle",
      attrs: {
        cx: "12",
        cy: "12",
        r: "3",
        transition: {
          duration: 0.4,
          ease: "easeInOut",
        },
      },
      key: "path2",
    },
  ],
  variants: {
    path: {
      initial: {
        scaleY: 1,
        opacity: 1,
      },
      animate: {
        scaleY: [1, 0.1, 1],
        opacity: [1, 0.3, 1],
      },
    },
    path2: {
      initial: {
        scale: 1,
        opacity: 1,
      },
      animate: {
        scale: [1, 0.3, 1],
        opacity: [1, 0.3, 1],
      },
    },
  },
}

/** eye-off (animate-ui) */
export const EyeOff: MotionIconData = {
  name: "eye-off",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M14.084 14.158a3 3 0 0 1-4.242-4.242",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
      },
    },
    {
      tag: "path",
      attrs: {
        d: "m2 2 20 20",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        pathLength: 1,
        opacity: 1,
        pathOffset: 0,
      },
      animate: {
        pathLength: [0, 2],
        opacity: [0, 1],
        pathOffset: [0, 2],
        transition: {
          duration: 0.6,
        },
      },
    },
  },
}

/** feather (animate-ui) */
export const Feather: MotionIconData = {
  name: "feather",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "feather",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M12.67 19a2 2 0 0 0 1.416-.588l6.154-6.172a6 6 0 0 0-8.49-8.49L5.586 9.914A2 2 0 0 0 5 11.328V18a1 1 0 0 0 1 1z",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M16 8 2 22",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M17.5 15H9",
          },
        },
      ],
    },
  ],
  variants: {
    feather: {
      initial: {
        rotate: 0,
        y: 0,
        x: 0,
      },
      animate: {
        rotate: [0, -8, 4, -3, 0],
        y: [0, -4, -2, -1, 0],
        x: [0, 2, -2, 1, 0],
        transition: {
          duration: 1.6,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** folder (hand-written) */
export const Folder: MotionIconData = {
  name: "folder",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z",
        style: {
          transformBox: "view-box",
        },
      },
      key: "folder",
    },
    {
      tag: "path",
      attrs: {
        d: "M8 10h8M8 13h5",
      },
      key: "document",
    },
  ],
  variants: {
    folder: {
      initial: {
        scaleY: 1,
        pathLength: 1,
      },
      animate: {
        scaleY: [1, 0.94, 1.03, 1],
        pathLength: [0.2, 1],
        transformOrigin: "12px 20px",
        transition: {
          duration: 0.82,
          ease: "easeOut",
        },
      },
    },
    document: {
      initial: {
        y: -5,
        opacity: 0,
        pathLength: 0,
      },
      animate: {
        y: [-5, 1, 0],
        opacity: [0, 1, 0.9],
        pathLength: [0, 1],
        transition: {
          duration: 0.68,
          delay: 0.18,
          ease: "easeOut",
        },
      },
    },
  },
}

/** frame (animate-ui) */
export const Frame: MotionIconData = {
  name: "frame",
  elements: [
    {
      tag: "line",
      attrs: {
        x1: "22",
        x2: "2",
        y1: "6",
        y2: "6",
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: "22",
        x2: "2",
        y1: "18",
        y2: "18",
      },
      key: "line2",
    },
    {
      tag: "line",
      attrs: {
        x1: "6",
        x2: "6",
        y1: "2",
        y2: "22",
      },
      key: "line3",
    },
    {
      tag: "line",
      attrs: {
        x1: "18",
        x2: "18",
        y1: "2",
        y2: "22",
      },
      key: "line4",
    },
  ],
  variants: {
    line1: {
      initial: {
        y: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
      animate: {
        y: -4,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
    },
    line2: {
      initial: {
        y: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
      animate: {
        y: 4,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
    },
    line3: {
      initial: {
        x: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
      animate: {
        x: -4,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
    },
    line4: {
      initial: {
        x: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
      animate: {
        x: 4,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 15,
        },
      },
    },
  },
}

/** grip-vertical (animate-ui) */
export const GripVertical: MotionIconData = {
  name: "grip-vertical",
  elements: [
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 0,
        },
        cx: 9,
        cy: 5,
        r: "1",
      },
      key: "part",
    },
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 1,
        },
        cx: 9,
        cy: 12,
        r: "1",
      },
      key: "part",
    },
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 2,
        },
        cx: 9,
        cy: 19,
        r: "1",
      },
      key: "part",
    },
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 3,
        },
        cx: 15,
        cy: 5,
        r: "1",
      },
      key: "part",
    },
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 4,
        },
        cx: 15,
        cy: 12,
        r: "1",
      },
      key: "part",
    },
    {
      tag: "circle",
      attrs: {
        custom: {
          index: 5,
        },
        cx: 15,
        cy: 19,
        r: "1",
      },
      key: "part",
    },
  ],
  variants: {
    part: {
      initial: {
        opacity: 1,
        scale: 1,
        transition: {
          duration: 0.25,
          ease: "easeOut",
        },
      },
      animate: ((ROWS: any) => (data: any) => {
    const row = data.index % ROWS;
    const col = Math.floor(data.index / ROWS);
    const delay = row * 0.15 + col * (ROWS * 0.15 - 0.2);

    return {
      opacity: [1, 0.4, 1],
      scale: [1, 0.85, 1],
      transition: { delay, duration: 1, ease: "easeInOut" },
    };
  })(3),
    },
  },
}

/** group (hand-written) */
export const Group: MotionIconData = {
  name: "group",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M3 7V5c0-1.1.9-2 2-2h2",
        style: {
          transformBox: "view-box",
        },
      },
      key: "frame",
    },
    {
      tag: "path",
      attrs: {
        d: "M17 3h2c1.1 0 2 .9 2 2v2",
        style: {
          transformBox: "view-box",
        },
      },
      key: "frame",
    },
    {
      tag: "path",
      attrs: {
        d: "M21 17v2c0 1.1-.9 2-2 2h-2",
        style: {
          transformBox: "view-box",
        },
      },
      key: "frame",
    },
    {
      tag: "path",
      attrs: {
        d: "M7 21H5c-1.1 0-2-.9-2-2v-2",
        style: {
          transformBox: "view-box",
        },
      },
      key: "frame",
    },
    {
      tag: "rect",
      attrs: {
        width: "7",
        height: "5",
        x: "7",
        y: "7",
        rx: "1",
      },
      key: "first",
    },
    {
      tag: "rect",
      attrs: {
        width: "7",
        height: "5",
        x: "10",
        y: "12",
        rx: "1",
      },
      key: "second",
    },
  ],
  variants: {
    frame: {
      initial: {
        scale: 1,
        opacity: 1,
      },
      animate: {
        scale: [0.88, 1.05, 1],
        opacity: [0.45, 1, 1],
        transformOrigin: "12px 12px",
        transition: {
          duration: 0.72,
          ease: "easeOut",
        },
      },
    },
    first: {
      initial: {
        x: 0,
        y: 0,
        opacity: 1,
      },
      animate: {
        x: [-4, 0.6, 0],
        y: [-2, 0, 0],
        opacity: [0, 1, 1],
        transition: {
          duration: 0.56,
          delay: 0.18,
          ease: "easeOut",
        },
      },
    },
    second: {
      initial: {
        x: 0,
        y: 0,
        opacity: 1,
      },
      animate: {
        x: [4, -0.6, 0],
        y: [2, 0, 0],
        opacity: [0, 1, 1],
        transition: {
          duration: 0.68,
          delay: 0.3,
          ease: "easeOut",
        },
      },
    },
  },
}

/** hand (animate-ui) */
export const Hand: MotionIconData = {
  name: "hand",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "path",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15",
          },
        },
      ],
    },
  ],
  variants: {
    path: {
      initial: {
        rotate: 0,
        originX: "50%",
        originY: "90%",
      },
      animate: {
        rotate: [0, -15, 10, -5, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** heart (animate-ui) */
export const Heart: MotionIconData = {
  name: "heart",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z",
          },
          key: "path",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 0.9, 1.2, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path: {},
  },
}

/** history (animate-ui) */
export const History: MotionIconData = {
  name: "history",
  elements: [
    {
      tag: "g",
      attrs: {
        transition: {
          type: "spring",
          stiffness: 250,
          damping: 25,
        },
      },
      key: "arrow",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "M3 3v5h5",
          },
        },
      ],
    },
    {
      tag: "line",
      attrs: {
        transition: {
          duration: 0.6,
          ease: [0.4, 0, 0.2, 1],
        },
        x1: "12",
        x2: "12",
        y1: "12",
        y2: "7",
      },
      key: "hand",
    },
    {
      tag: "line",
      attrs: {
        transition: {
          duration: 0.5,
          ease: "easeInOut",
        },
        x1: "12",
        x2: "16",
        y1: "12",
        y2: "14",
      },
      key: "minuteHand",
    },
  ],
  variants: {
    arrow: {
      initial: {
        rotate: "0deg",
      },
      animate: {
        rotate: "-50deg",
      },
    },
    hand: {
      initial: {
        rotate: 0,
        originX: "0%",
        originY: "100%",
      },
      animate: {
        rotate: -360,
        originX: "0%",
        originY: "100%",
      },
    },
    minuteHand: {
      initial: {
        rotate: 0,
        originX: "0%",
        originY: "0%",
      },
      animate: {
        rotate: -45,
        originX: "0%",
        originY: "0%",
      },
    },
  },
}

/** layers (animate-ui) */
export const Layers: MotionIconData = {
  name: "layers",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z",
      },
      key: "path1",
    },
    {
      tag: "path",
      attrs: {
        d: "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12",
      },
      key: "path2",
    },
    {
      tag: "path",
      attrs: {
        d: "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17",
      },
      key: "path3",
    },
  ],
  variants: {
    path1: {
      initial: {
        y: 0,
      },
      animate: {
        y: 5,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path2: {},
    path3: {
      initial: {
        y: 0,
      },
      animate: {
        y: -5,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** layout-grid (animate-ui) */
export const LayoutGrid: MotionIconData = {
  name: "layout-grid",
  elements: [
    {
      tag: "rect",
      attrs: {
        height: "7",
        rx: "1",
        width: "7",
        x: "3",
        y: "3",
      },
      key: "rect_1",
    },
    {
      tag: "rect",
      attrs: {
        height: "7",
        rx: "1",
        width: "7",
        x: "14",
        y: "3",
      },
      key: "rect_2",
    },
    {
      tag: "rect",
      attrs: {
        height: "7",
        rx: "1",
        width: "7",
        x: "14",
        y: "14",
      },
      key: "rect_3",
    },
    {
      tag: "rect",
      attrs: {
        height: "7",
        rx: "1",
        width: "7",
        x: "3",
        y: "14",
      },
      key: "rect_4",
    },
  ],
  variants: {
    rect_1: {
      initial: {
        translateX: 0,
        translateY: 0,
      },
      animate: {
        translateX: [0, 11, 11, 0],
        translateY: [0, 0, 0, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          times: [0, 0.4, 0.6, 1],
        },
      },
    },
    rect_2: {
      initial: {
        translateX: 0,
        translateY: 0,
      },
      animate: {
        translateX: [0, 0, 0, 0],
        translateY: [0, 11, 11, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          times: [0, 0.4, 0.6, 1],
        },
      },
    },
    rect_3: {
      initial: {
        translateX: 0,
        translateY: 0,
      },
      animate: {
        translateX: [0, -11, -11, 0],
        translateY: [0, 0, 0, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          times: [0, 0.4, 0.6, 1],
        },
      },
    },
    rect_4: {
      initial: {
        translateX: 0,
        translateY: 0,
      },
      animate: {
        translateX: [0, 0, 0, 0],
        translateY: [0, -11, -11, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          times: [0, 0.4, 0.6, 1],
        },
      },
    },
  },
}

/** lightbulb (animate-ui) */
export const Lightbulb: MotionIconData = {
  name: "lightbulb",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5",
      },
      key: "path1",
    },
    {
      tag: "path",
      attrs: {
        d: "M9 18h6",
      },
      key: "path2",
    },
    {
      tag: "path",
      attrs: {
        d: "M10 22h4",
      },
      key: "path3",
    },
  ],
  variants: {
    path1: {
      initial: {
        rotate: 0,
        fill: "transparent",
      },
      animate: {
        transformOrigin: "bottom center",
        fill: "currentColor",
        rotate: [0, -20, 15, -7, 0],
        fillOpacity: [0, 1, 0, 1, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          rotate: {
            duration: 0.8,
            ease: "easeInOut",
            times: [0, 0.4, 0.6, 0.8, 1],
          },
          fillOpacity: {
            duration: 0.3,
            ease: "easeInOut",
            times: [0, 0.4, 0.6, 0.8, 1],
            delay: 0.4,
          },
        },
      },
    },
    path2: {
      initial: {
        rotate: 0,
      },
      animate: {
        transformOrigin: "bottom center",
        rotate: [0, 0, 10, -5, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
          times: [0, 0.4, 0.6, 0.8, 1],
        },
      },
    },
    path3: {},
  },
}

/** link-2 (animate-ui) */
export const Link2: MotionIconData = {
  name: "link-2",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M9 17H7A5 5 0 0 1 7 7h2",
      },
      key: "left",
    },
    {
      tag: "path",
      attrs: {
        d: "M15 7h2a5 5 0 1 1 0 10h-2",
      },
      key: "right",
    },
    {
      tag: "line",
      attrs: {
        x1: 8,
        y1: 12,
        x2: 16,
        y2: 12,
        style: {
          transformOrigin: "12px 12px",
          transformBox: "view-box",
        },
      },
      key: "middle",
    },
    {
      tag: "g",
      attrs: {
        style: {
          rotate: 45,
          transformOrigin: "12px 12px",
          transformBox: "view-box",
        },
      },
      children: [
        {
          tag: "line",
          attrs: {
            x1: 8,
            y1: 2,
            x2: 8,
            y2: 5,
            style: {
              transformOrigin: "8px 3.5px",
              transformBox: "view-box",
            },
          },
          key: "burstTop",
        },
        {
          tag: "line",
          attrs: {
            x1: 2,
            y1: 8,
            x2: 5,
            y2: 8,
            style: {
              transformOrigin: "3.5px 8px",
              transformBox: "view-box",
            },
          },
          key: "burstLeft",
        },
        {
          tag: "line",
          attrs: {
            x1: 16,
            y1: 19,
            x2: 16,
            y2: 22,
            style: {
              transformOrigin: "16px 20.5px",
              transformBox: "view-box",
            },
          },
          key: "burstBottom",
        },
        {
          tag: "line",
          attrs: {
            x1: 19,
            y1: 16,
            x2: 22,
            y2: 16,
            style: {
              transformOrigin: "20.5px 16px",
              transformBox: "view-box",
            },
          },
          key: "burstRight",
        },
      ],
    },
  ],
  variants: {
    left: {
      initial: {
        rotate: 0,
        transformOrigin: "9px 12px",
      },
      animate: {
        rotate: [0, 10, 0],
        transformOrigin: "9px 12px",
        transition: {
          duration: 0.4,
          ease: "easeInOut",
        },
      },
    },
    right: {
      initial: {
        rotate: 0,
        transformOrigin: "15px 12px",
      },
      animate: {
        rotate: [0, -6, 0],
        transformOrigin: "15px 12px",
        transition: {
          duration: 0.4,
          ease: "easeInOut",
        },
      },
    },
    middle: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, 12, 0],
        transition: {
          duration: 0.4,
          ease: "easeInOut",
        },
      },
    },
    burstTop: {
      initial: {
        opacity: 0,
      },
      animate: {
        opacity: 0,
      },
    },
    burstLeft: {
      initial: {
        opacity: 0,
      },
      animate: {
        opacity: 0,
      },
    },
    burstBottom: {
      initial: {
        opacity: 0,
      },
      animate: {
        opacity: 0,
      },
    },
    burstRight: {
      initial: {
        opacity: 0,
      },
      animate: {
        opacity: 0,
      },
    },
  },
}

/** lock (animate-ui) */
export const Lock: MotionIconData = {
  name: "lock",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "rect",
          attrs: {
            width: "18",
            height: "11",
            x: "3",
            y: "11",
            rx: "2",
            ry: "2",
          },
          key: "rect",
        },
        {
          tag: "path",
          attrs: {
            d: "M7 11V7a5 5 0 0 1 10 0v4",
          },
          key: "path",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
        scale: 1,
      },
      animate: {
        rotate: [0, -5, 7, 0],
        scale: [1, 0.9, 1, 1],
        transition: {
          duration: 1.2,
          ease: "easeInOut",
        },
      },
    },
    path: {
      initial: {
        pathLength: 1,
      },
      animate: {
        pathLength: [1, 0.8, 1, 1],
        transition: {
          duration: 1.2,
          ease: "easeInOut",
        },
      },
    },
    rect: {},
  },
}

/** map-pin (animate-ui) */
export const MapPin: MotionIconData = {
  name: "map-pin",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "circle",
          attrs: {
            cx: 12,
            cy: 10,
            r: 3,
          },
          key: "circle",
        },
        {
          tag: "path",
          attrs: {
            d: "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0",
          },
          key: "path",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        scale: 1,
        rotate: 0,
        x: 0,
        y: 0,
        transformOrigin: "bottom center",
      },
      animate: {
        scale: [1, 0.75, 1, 1],
        rotate: [0, 30, -15, 0],
        x: [0, 0, 0, 0],
        y: [0, -6, 0, 0],
        transformOrigin: "bottom center",
        transition: {
          ease: "easeInOut",
          duration: 1,
        },
      },
    },
    circle: {},
    path: {},
  },
}

/** maximize-2 (animate-ui) */
export const Maximize2: MotionIconData = {
  name: "maximize-2",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M3 16.2V21m0 0h4.8M3 21l6-6",
        transition: {
          type: "spring",
          stiffness: 250,
          damping: 25,
        },
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "M21 7.8V3m0 0h-4.8M21 3l-6 6",
        transition: {
          type: "spring",
          stiffness: 250,
          damping: 25,
        },
      },
      key: "path2",
    },
  ],
  variants: {
    path: {
      initial: {
        translateX: "0%",
        translateY: "0%",
      },
      animate: {
        translateX: "-2px",
        translateY: "2px",
      },
    },
    path2: {
      initial: {
        translateX: "0%",
        translateY: "0%",
      },
      animate: {
        translateX: "2px",
        translateY: "-2px",
      },
    },
  },
}

/** menu (animate-ui) */
export const Menu: MotionIconData = {
  name: "menu",
  elements: [
    {
      tag: "line",
      attrs: {
        x1: 4,
        y1: 6,
        x2: 20,
        y2: 6,
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: 4,
        y1: 12,
        x2: 20,
        y2: 12,
      },
      key: "line2",
    },
    {
      tag: "line",
      attrs: {
        x1: 4,
        y1: 18,
        x2: 20,
        y2: 18,
      },
      key: "line3",
    },
  ],
  variants: {
    line1: {
      initial: {
        rotate: 0,
        x: 0,
        y: 0,
      },
      animate: {
        rotate: -45,
        x: -2.35,
        y: 0.35,
        transformOrigin: "top right",
        transition: {
          type: "spring",
          stiffness: 200,
          damping: 20,
        },
      },
    },
    line2: {
      initial: {
        opacity: 1,
      },
      animate: {
        opacity: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.2,
        },
      },
    },
    line3: {
      initial: {
        rotate: 0,
        x: 0,
        y: 0,
      },
      animate: {
        rotate: 45,
        x: -2.35,
        y: -0.35,
        transformOrigin: "bottom right",
        transition: {
          type: "spring",
          stiffness: 200,
          damping: 20,
        },
      },
    },
  },
}

/** moon (hand-written) */
export const Moon: MotionIconData = {
  name: "moon",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
      },
      key: "path",
    },
  ],
  variants: {
    path: {
      initial: {
        rotate: 0,
        transition: {
          duration: 0.5,
          ease: "easeInOut",
        },
      },
      animate: {
        rotate: [0, -30, 400, 360],
        transition: {
          duration: 1.2,
          times: [0, 0.25, 0.75, 1],
          ease: ["easeInOut", "easeInOut", "easeInOut"],
        },
      },
    },
  },
}

/** pen-tool (animate-ui) */
export const PenTool: MotionIconData = {
  name: "pen-tool",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "svg",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18",
          },
        },
        {
          tag: "path",
          attrs: {
            d: "m2.3 2.3 7.286 7.286",
            transition: {
              duration: 0.8,
            },
          },
          key: "path",
        },
        {
          tag: "circle",
          attrs: {
            cx: "11",
            cy: "11",
            r: "2",
          },
        },
      ],
    },
  ],
  variants: {
    svg: {
      initial: {
        rotate: 0,
        translateX: 0,
        translateY: 0,
      },
      animate: {
        rotate: [0, 0, 8, -3, 8, 0],
        translateY: [0, 2, 0, -1, 0],
      },
    },
    path: {
      initial: {
        pathLength: 1,
        opacity: 1,
        pathOffset: 0,
      },
      animate: {
        pathLength: [0, 0, 1],
        opacity: [0, 1],
        pathOffset: [0, 1, 0],
      },
    },
  },
}

/** play (animate-ui) */
export const Play: MotionIconData = {
  name: "play",
  elements: [
    {
      tag: "polygon",
      attrs: {
        points: "6 3 20 12 6 21 6 3",
      },
      key: "polygon",
    },
  ],
  variants: {
    polygon: {
      initial: {
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        x: 3,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** plus (hand-written) */
export const Plus: MotionIconData = {
  name: "plus",
  elements: [
    {
      tag: "line",
      attrs: {
        x1: 12,
        y1: 19,
        x2: 12,
        y2: 5,
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: 5,
        y1: 12,
        x2: 19,
        y2: 12,
      },
      key: "line2",
    },
  ],
  variants: {
    line1: {
      initial: {
        rotate: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
          delay: 0.1,
        },
      },
      animate: {
        rotate: 90,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
          delay: 0.1,
        },
      },
    },
    line2: {
      initial: {
        rotate: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
      animate: {
        rotate: 90,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
  },
}

/** redo (animate-ui) */
export const Redo: MotionIconData = {
  name: "redo",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M21 7v6h-6",
        transition: {
          duration: 0.6,
          ease: [0.25, 0.1, 0.25, 1],
        },
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "M3 17a9 9 0 0 1 9-9 9 9 0 0 1 6 2.3l3 2.7",
        transition: {
          duration: 0.6,
          ease: [0.25, 0.1, 0.25, 1],
        },
      },
      key: "path2",
    },
  ],
  variants: {
    path: {
      initial: {
        translateX: 0,
        translateY: 0,
        rotate: 0,
      },
      animate: {
        translateX: [0, -2.1, 0],
        translateY: [0, -1.4, 0],
        rotate: [0, -12, 0],
      },
    },
    path2: {
      initial: {
        pathLength: 1,
      },
      animate: {
        pathLength: [1, 0.8, 1],
      },
    },
  },
}

/** refresh-cw (animate-ui) */
export const RefreshCw: MotionIconData = {
  name: "refresh-cw",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M21 3v5h-5",
          },
          key: "path2",
        },
        {
          tag: "path",
          attrs: {
            d: "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
          },
          key: "path3",
        },
        {
          tag: "path",
          attrs: {
            d: "M8 16H3v5",
          },
          key: "path4",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
      animate: {
        rotate: 45,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
    path4: {},
  },
}

/** rotate-ccw (animate-ui) */
export const RotateCcw: MotionIconData = {
  name: "rotate-ccw",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M3 3v5h5",
          },
          key: "path2",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
      animate: {
        rotate: -45,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
    },
    path1: {},
    path2: {},
  },
}

/** rotate-cw (animate-ui) */
export const RotateCw: MotionIconData = {
  name: "rotate-cw",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M21 3v5h-5",
          },
          key: "path2",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
      animate: {
        rotate: 45,
        transition: {
          type: "spring",
          stiffness: 150,
          damping: 25,
        },
      },
    },
    path1: {},
    path2: {},
  },
}

/** scissors (animate-ui) */
export const Scissors: MotionIconData = {
  name: "scissors",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group1",
      children: [
        {
          tag: "circle",
          attrs: {
            cx: "6",
            cy: "6",
            r: "3",
          },
          key: "circle1",
        },
        {
          tag: "path",
          attrs: {
            d: "M8.12 8.12 12 12",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M14.8 14.8 20 20",
          },
          key: "path2",
        },
      ],
    },
    {
      tag: "g",
      attrs: {},
      key: "group2",
      children: [
        {
          tag: "circle",
          attrs: {
            cx: "6",
            cy: "18",
            r: "3",
          },
          key: "circle2",
        },
        {
          tag: "path",
          attrs: {
            d: "M20 4 8.12 15.88",
          },
          key: "path3",
        },
      ],
    },
  ],
  variants: {
    group1: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, -26, 0],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    group2: {
      initial: {
        rotate: 0,
      },
      animate: {
        rotate: [0, 26, 0],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
  },
}

/** search (animate-ui) */
export const Search: MotionIconData = {
  name: "search",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "m21 21-4.34-4.34",
          },
          key: "path",
        },
        {
          tag: "circle",
          attrs: {
            cx: 11,
            cy: 11,
            r: 8,
          },
          key: "circle",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        rotate: 0,
      },
      animate: {
        transformOrigin: "bottom right",
        rotate: [0, 17, -10, 5, -1, 0],
        transition: {
          duration: 0.8,
          ease: "easeInOut",
        },
      },
    },
    path: {},
    circle: {},
  },
}

/** shrink (animate-ui) */
export const Shrink: MotionIconData = {
  name: "shrink",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m15 15 6 6m-6-6v4.8m0-4.8h4.8",
      },
      key: "path1",
    },
    {
      tag: "path",
      attrs: {
        d: "M9 19.8V15m0 0H4.2M9 15l-6 6",
      },
      key: "path3",
    },
    {
      tag: "path",
      attrs: {
        d: "M15 4.2V9m0 0h4.8M15 9l6-6",
      },
      key: "path2",
    },
    {
      tag: "path",
      attrs: {
        d: "M9 4.2V9m0 0H4.2M9 9 3 3",
      },
      key: "path4",
    },
  ],
  variants: {
    path1: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: -1,
        x: -1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path2: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 1,
        x: -1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path3: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: -1,
        x: 1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path4: {
      initial: {
        y: 0,
        x: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: 1,
        x: 1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** sliders-horizontal (animate-ui) */
export const SlidersHorizontal: MotionIconData = {
  name: "sliders-horizontal",
  elements: [
    {
      tag: "line",
      attrs: {
        x1: "3",
        y1: "5",
        x2: "10",
        y2: "5",
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: "14",
        y1: "3",
        x2: "14",
        y2: "7",
      },
      key: "line2",
    },
    {
      tag: "line",
      attrs: {
        x1: "14",
        y1: "5",
        x2: "21",
        y2: "5",
      },
      key: "line3",
    },
    {
      tag: "line",
      attrs: {
        x1: "3",
        y1: "12",
        x2: "8",
        y2: "12",
      },
      key: "line4",
    },
    {
      tag: "line",
      attrs: {
        x1: "8",
        y1: "10",
        x2: "8",
        y2: "14",
      },
      key: "line5",
    },
    {
      tag: "line",
      attrs: {
        x1: "12",
        y1: "12",
        x2: "21",
        y2: "12",
      },
      key: "line6",
    },
    {
      tag: "line",
      attrs: {
        x1: "3",
        y1: "19",
        x2: "12",
        y2: "19",
      },
      key: "line7",
    },
    {
      tag: "line",
      attrs: {
        x1: "16",
        y1: "17",
        x2: "16",
        y2: "21",
      },
      key: "line8",
    },
    {
      tag: "line",
      attrs: {
        x1: "16",
        y1: "19",
        x2: "21",
        y2: "19",
      },
      key: "line9",
    },
  ],
  variants: {
    line1: {
      initial: {
        x2: 10,
      },
      animate: {
        x2: 4,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line2: {
      initial: {
        x1: 14,
        x2: 14,
      },
      animate: {
        x1: 8,
        x2: 8,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line3: {
      initial: {
        x1: 14,
      },
      animate: {
        x1: 8,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line4: {
      initial: {
        x2: 8,
      },
      animate: {
        x2: 16,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line5: {
      initial: {
        x1: 8,
        x2: 8,
      },
      animate: {
        x1: 16,
        x2: 16,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line6: {
      initial: {
        x1: 12,
      },
      animate: {
        x1: 20,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line7: {
      initial: {
        x2: 12,
      },
      animate: {
        x2: 7,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line8: {
      initial: {
        x1: 16,
        x2: 16,
      },
      animate: {
        x1: 11,
        x2: 11,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line9: {
      initial: {
        x1: 16,
      },
      animate: {
        x1: 11,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
  },
}

/** sparkles (animate-ui) */
export const Sparkles: MotionIconData = {
  name: "sparkles",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
          },
          key: "path",
        },
      ],
    },
    {
      tag: "path",
      attrs: {
        d: "M20 2v4 M22 4h-4",
      },
      key: "plus",
    },
    {
      tag: "circle",
      attrs: {
        cx: "4",
        cy: "20",
        r: "2",
      },
      key: "circle",
    },
  ],
  variants: {
    group: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 0.9, 1.1, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path: {},
    plus: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: 0,
        scale: 0,
        transition: {
          opacity: {
            duration: 0.2,
            ease: "easeInOut",
            repeat: 1,
            repeatType: "reverse",
            repeatDelay: 0.2,
            delay: 0.15,
          },
          scale: {
            duration: 0.2,
            ease: "easeInOut",
            repeat: 1,
            repeatType: "reverse",
            repeatDelay: 0.2,
            delay: 0.15,
          },
        },
      },
    },
    circle: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: 0,
        scale: 0,
        transition: {
          opacity: {
            duration: 0.2,
            ease: "easeInOut",
            repeat: 1,
            repeatType: "reverse",
            repeatDelay: 0.2,
          },
          scale: {
            duration: 0.2,
            ease: "easeInOut",
            repeat: 1,
            repeatType: "reverse",
            repeatDelay: 0.2,
          },
        },
      },
    },
  },
}

/** star (animate-ui) */
export const Star: MotionIconData = {
  name: "star",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z",
          },
          key: "path",
        },
      ],
    },
  ],
  variants: {
    group: {
      initial: {
        scale: 1,
      },
      animate: {
        scale: [1, 0.9, 1.2, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
        },
      },
    },
    path: {},
  },
}

/** sun (hand-written) */
export const Sun: MotionIconData = {
  name: "sun",
  elements: [
    {
      tag: "circle",
      attrs: {
        cx: "12",
        cy: "12",
        r: "4",
      },
      key: "circle",
    },
    {
      tag: "line",
      attrs: {
        x1: "12",
        y1: "4",
        x2: "12",
        y2: "2",
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: "17.7",
        y1: "6.3",
        x2: "19.1",
        y2: "4.9",
      },
      key: "line2",
    },
    {
      tag: "line",
      attrs: {
        x1: "20",
        y1: "12",
        x2: "22",
        y2: "12",
      },
      key: "line3",
    },
    {
      tag: "line",
      attrs: {
        x1: "17.7",
        y1: "17.7",
        x2: "19.1",
        y2: "19.1",
      },
      key: "line4",
    },
    {
      tag: "line",
      attrs: {
        x1: "12",
        y1: "20",
        x2: "12",
        y2: "22",
      },
      key: "line5",
    },
    {
      tag: "line",
      attrs: {
        x1: "6.3",
        y1: "17.7",
        x2: "4.9",
        y2: "19.1",
      },
      key: "line6",
    },
    {
      tag: "line",
      attrs: {
        x1: "4",
        y1: "12",
        x2: "2",
        y2: "12",
      },
      key: "line7",
    },
    {
      tag: "line",
      attrs: {
        x1: "6.3",
        y1: "6.3",
        x2: "4.9",
        y2: "4.9",
      },
      key: "line8",
    },
  ],
  variants: {
    circle: {},
    line1: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0,
        },
      },
    },
    line2: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.15,
        },
      },
    },
    line3: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.3,
        },
      },
    },
    line4: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.44999999999999996,
        },
      },
    },
    line5: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.6,
        },
      },
    },
    line6: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.75,
        },
      },
    },
    line7: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 0.8999999999999999,
        },
      },
    },
    line8: {
      initial: {
        opacity: 1,
        scale: 1,
      },
      animate: {
        opacity: [0, 1],
        pathLength: [0, 1],
        transition: {
          duration: 0.6,
          ease: "easeInOut",
          delay: 1.05,
        },
      },
    },
  },
}

/** terminal (hand-written) */
export const Terminal: MotionIconData = {
  name: "terminal",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M12 19h8",
      },
      key: "path1",
    },
    {
      tag: "path",
      attrs: {
        d: "m4 17 6-6-6-6",
      },
      key: "path2",
    },
  ],
  variants: {
    path1: {
      initial: {
        opacity: 1,
      },
      animate: {
        opacity: [1, 0, 1, 0, 1],
        transition: {
          duration: 1.5,
          ease: "easeInOut",
        },
      },
    },
    path2: {},
  },
}

/** timer (animate-ui) */
export const Timer: MotionIconData = {
  name: "timer",
  elements: [
    {
      tag: "circle",
      attrs: {
        cx: 12,
        cy: 14,
        r: 8,
      },
      key: "circle",
    },
    {
      tag: "line",
      attrs: {
        x1: 12,
        x2: 15,
        y1: 14,
        y2: 11,
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: 10,
        x2: 14,
        y1: 2,
        y2: 2,
      },
      key: "line2",
    },
  ],
  variants: {
    circle: {},
    line1: {
      initial: {
        rotate: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.6,
        },
      },
      animate: {
        transformOrigin: "bottom left",
        rotate: 360,
        transition: {
          ease: "easeInOut",
          duration: 0.6,
          delay: 0.15,
        },
      },
    },
    line2: {
      initial: {
        y: 0,
      },
      animate: {
        y: [0, 1.5, 0],
        transition: {
          ease: "easeInOut",
          duration: 0.3,
        },
      },
    },
  },
}

/** toggle-left (animate-ui) */
export const ToggleLeft: MotionIconData = {
  name: "toggle-left",
  elements: [
    {
      tag: "rect",
      attrs: {
        width: 20,
        height: 14,
        x: 2,
        y: 5,
        rx: 7,
      },
      key: "rect",
    },
    {
      tag: "circle",
      attrs: {
        cx: 9,
        cy: 12,
        r: 3,
      },
      key: "circle",
    },
  ],
  variants: {
    rect: {},
    circle: {
      initial: {
        x: 0,
      },
      animate: {
        x: [0, 7, 6],
        transition: {
          duration: 0.5,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** toggle-right (animate-ui) */
export const ToggleRight: MotionIconData = {
  name: "toggle-right",
  elements: [
    {
      tag: "rect",
      attrs: {
        width: 20,
        height: 14,
        x: 2,
        y: 5,
        rx: 7,
      },
      key: "rect",
    },
    {
      tag: "circle",
      attrs: {
        cx: 15,
        cy: 12,
        r: 3,
      },
      key: "circle",
    },
  ],
  variants: {
    rect: {},
    circle: {
      initial: {
        x: 0,
      },
      animate: {
        x: [0, -7, -6],
        transition: {
          duration: 0.5,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** trash-2 (animate-ui) */
export const Trash2: MotionIconData = {
  name: "trash-2",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "M3 6h18",
          },
          key: "path2",
        },
      ],
    },
    {
      tag: "path",
      attrs: {
        d: "M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6",
      },
      key: "path3",
    },
    {
      tag: "line",
      attrs: {
        x1: 10,
        x2: 10,
        y1: 11,
        y2: 17,
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: 14,
        x2: 14,
        y1: 11,
        y2: 17,
      },
      key: "line2",
    },
  ],
  variants: {
    group: {
      initial: {
        y: 0,
      },
      animate: {
        y: -1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {
      initial: {
        y: 0,
        d: "M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6",
      },
      animate: {
        y: 1,
        d: "M19 8v12c0 1-1 2-2 2H7c-1 0-2-1-2-2V8",
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    line1: {
      initial: {
        y: 0,
      },
      animate: {
        y: 1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    line2: {
      initial: {
        y: 0,
      },
      animate: {
        y: 1,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
  },
}

/** undo (animate-ui) */
export const Undo: MotionIconData = {
  name: "undo",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "M3 7v6h6",
        transition: {
          duration: 0.6,
          ease: [0.25, 0.1, 0.25, 1],
        },
      },
      key: "path",
    },
    {
      tag: "path",
      attrs: {
        d: "M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13",
        transition: {
          duration: 0.6,
          ease: [0.25, 0.1, 0.25, 1],
        },
      },
      key: "path2",
    },
  ],
  variants: {
    path: {
      initial: {
        translateX: 0,
        translateY: 0,
        rotate: 0,
      },
      animate: {
        translateX: [0, 2.1, 0],
        translateY: [0, -1.4, 0],
        rotate: [0, 12, 0],
      },
    },
    path2: {
      initial: {
        pathLength: 1,
      },
      animate: {
        pathLength: [1, 0.8, 1],
      },
    },
  },
}

/** upload (animate-ui) */
export const Upload: MotionIconData = {
  name: "upload",
  elements: [
    {
      tag: "g",
      attrs: {},
      key: "group",
      children: [
        {
          tag: "path",
          attrs: {
            d: "M12 3v12",
          },
          key: "path1",
        },
        {
          tag: "path",
          attrs: {
            d: "m17 8-5-5-5 5",
          },
          key: "path2",
        },
      ],
    },
    {
      tag: "path",
      attrs: {
        d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
      },
      key: "path3",
    },
  ],
  variants: {
    group: {
      initial: {
        y: 0,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
      animate: {
        y: -2,
        transition: {
          duration: 0.3,
          ease: "easeInOut",
        },
      },
    },
    path1: {},
    path2: {},
    path3: {},
  },
}

/** wand-sparkles (hand-written) */
export const WandSparkles: MotionIconData = {
  name: "wand-sparkles",
  elements: [
    {
      tag: "path",
      attrs: {
        d: "m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72",
      },
      key: "wand",
    },
    {
      tag: "path",
      attrs: {
        d: "m14 7 3 3",
      },
      key: "wand",
    },
    {
      tag: "path",
      attrs: {
        d: "M5 6v4",
      },
      style: {
        transformOrigin: "5px 8px",
      },
      key: "sparkleA",
    },
    {
      tag: "path",
      attrs: {
        d: "M7 8H3",
      },
      style: {
        transformOrigin: "5px 8px",
      },
      key: "sparkleA",
    },
    {
      tag: "path",
      attrs: {
        d: "M10 2v2",
      },
      style: {
        transformOrigin: "10px 3px",
      },
      key: "sparkleB",
    },
    {
      tag: "path",
      attrs: {
        d: "M11 3H9",
      },
      style: {
        transformOrigin: "10px 3px",
      },
      key: "sparkleB",
    },
    {
      tag: "path",
      attrs: {
        d: "M19 14v4",
      },
      style: {
        transformOrigin: "19px 16px",
      },
      key: "sparkleC",
    },
    {
      tag: "path",
      attrs: {
        d: "M21 16h-4",
      },
      style: {
        transformOrigin: "19px 16px",
      },
      key: "sparkleC",
    },
  ],
  variants: {
    wand: {
      initial: {
        x: 0,
        y: 0,
        rotate: 0,
      },
      animate: {
        x: [0, -0.6, 0.5, -0.4, 0.4, -0.3, 0.2, 0],
        y: [0, 0.4, -0.5, 0.3, -0.3, 0.2, -0.1, 0],
        rotate: [0, -1.5, 1.2, -1, 0.8, -0.5, 0.3, 0],
        transformOrigin: "19.5px 4.5px",
        transition: {
          duration: 1.1,
          ease: "easeInOut",
        },
      },
    },
    sparkleA: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.15,
          ease: "easeOut",
        },
      },
    },
    sparkleB: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.35,
          ease: "easeOut",
        },
      },
    },
    sparkleC: {
      initial: {
        scale: 0,
        opacity: 0,
        rotate: -45,
      },
      animate: {
        scale: [0, 1.3, 1],
        opacity: [0, 1, 1],
        rotate: [-45, 0, 0],
        transition: {
          duration: 0.45,
          delay: 0.55,
          ease: "easeOut",
        },
      },
    },
  },
}

/** x (hand-written) */
export const X: MotionIconData = {
  name: "x",
  elements: [
    {
      tag: "line",
      attrs: {
        x1: 6,
        y1: 18,
        x2: 18,
        y2: 6,
      },
      key: "line1",
    },
    {
      tag: "line",
      attrs: {
        x1: 6,
        y1: 6,
        x2: 18,
        y2: 18,
      },
      key: "line2",
    },
  ],
  variants: {
    line1: {
      initial: {
        rotate: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
      animate: {
        rotate: 90,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
        },
      },
    },
    line2: {
      initial: {
        rotate: 0,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
          delay: 0.1,
        },
      },
      animate: {
        rotate: 90,
        transition: {
          ease: "easeInOut",
          duration: 0.4,
          delay: 0.1,
        },
      },
    },
  },
}
