// Writes src/lib/text/fontPreviews.ts: every bundled family's NAME, set in that
// family, as outline path data — what the editor's font picker draws.
//
// Drawing the list with the fonts themselves would mean fetching all of them
// (~5 MB) the first time the picker opens. Instead the names are laid out once,
// here, with the same HarfBuzz layout the editor uses, and shipped as a few KB
// of path data. Re-run after adding a font to BUNDLED_FONTS:
//
//   pnpm gen:fontpreviews

import { readFileSync, writeFileSync } from 'node:fs'
import { BUNDLED_FONTS } from '../src/lib/text/fonts.ts'
import { faceFromBytes } from '../src/lib/text/engine.ts'
import { layoutText } from '../src/lib/text/layout.ts'
import { newTextData, replaceText } from '../src/lib/text/edit.ts'
import { subPathsToD } from '../src/lib/path/model.ts'
import { subPathsTightBounds } from '../src/lib/path/geometry.ts'

const SIZE = 100
const out: Record<string, { d: string; w: number; h: number; ascent: number; axes: string[]; italic: boolean }> = {}

for (const f of BUNDLED_FONTS) {
  const b = readFileSync(new URL(`../public/fonts/${f.file}`, import.meta.url))
  const face = faceFromBytes(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer)
  const data = replaceText(newTextData({ x: 0, y: 0 }, SIZE, { font: f.id }), 0, 0, f.family)
  const layout = layoutText(data, () => ({ face, synthItalic: false }), String)
  const subs = layout.children.flatMap((c) => c.subPaths)
  const box = subPathsTightBounds(subs)
  // A fixed line box (ascender to descender), not the ink box, so every name
  // sits on one shared baseline in the list.
  const ascent = (face.ascender / face.upem) * SIZE
  const descent = (-face.descender / face.upem) * SIZE
  out[f.id] = {
    d: subPathsToD(subs, 0),
    w: Math.ceil(box ? box.x + box.w : 0),
    h: Math.ceil(ascent + descent),
    ascent: Math.round(ascent * 10) / 10,
    axes: face.axes.map((a) => `${a.tag} ${a.min}–${a.max}`),
    italic: !!f.italicFile,
  }
}

const body = `// GENERATED by scripts/gen-font-previews.ts — do not edit; re-run it instead.
//
// Each bundled family's name set in that family, as path data (em size ${SIZE},
// baseline at y = 0), for the font picker. \`h\` is the line box
// (ascender + descender) and \`ascent\` where the baseline sits in it.

export interface FontPreview {
  d: string
  w: number
  h: number
  ascent: number
  /** Variable axes as "tag min–max". */
  axes: string[]
  italic: boolean
}

export const FONT_PREVIEWS: Record<string, FontPreview> = ${JSON.stringify(out, null, 2)}
`
writeFileSync(new URL('../src/lib/text/fontPreviews.ts', import.meta.url), body)
console.log(`wrote ${Object.keys(out).length} previews, ${Math.round(body.length / 1024)} KB`)
