// Ready-made icon sheets for the intake's empty state. Most people don't have
// an icon sheet lying around, so the cards give them one to try — the same
// pattern the logo panels use (`ExampleGrid`), but the pick lands in the sheet
// store, never on the working logo.
//
// The sheets are exactly what an image model hands you when you ask for an icon
// set: generated by Gemini from a one-line prompt and re-encoded smaller (2048px
// WebP), nothing redrawn. Each one exercises a different part of the splitter.

import { useCallback, useState } from 'react'
import { useSheetStore } from '../../sheetStore'
import { ExampleCard } from '../ExamplesDialog'
import { readSheetFile } from './sheetIo'

interface SheetExample {
  /** File under public/examples/sheets/. */
  file: string
  name: string
  /** One-liner: what this sheet shows off in the splitter. */
  blurb: string
}

export const SHEET_EXAMPLES: SheetExample[] = [
  {
    file: 'weather.webp',
    name: 'Weather',
    blurb: 'Black glyphs with a title and captions — the text rows are set aside.',
  },
  {
    file: 'travel.webp',
    name: 'Travel',
    blurb: 'Sixteen flat colour icons on cream paper — the colour path.',
  },
  {
    file: 'smart-home.webp',
    name: 'Smart home',
    blurb: 'White glyphs and captions on dark paper — a dark background.',
  },
  {
    file: 'productivity.webp',
    name: 'Productivity',
    blurb: 'Thin line icons — each one is several pieces, grouped back into one.',
  },
]

const MIME: Record<string, string> = {
  webp: 'image/webp',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  svg: 'image/svg+xml',
}

const sheetUrl = (file: string) => `${import.meta.env.BASE_URL}examples/sheets/${file}`

/** The example-sheet cards; clicking one loads it as the sheet. */
export function SheetExampleGrid({ className }: { className?: string }) {
  const setSource = useSheetStore((s) => s.setSource)
  const [loadingFile, setLoadingFile] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const pick = useCallback(
    async (ex: SheetExample) => {
      if (loadingFile) return
      setError(null)
      setLoadingFile(ex.file)
      try {
        const res = await fetch(sheetUrl(ex.file))
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const blob = await res.blob()
        const ext = ex.file.slice(ex.file.lastIndexOf('.') + 1).toLowerCase()
        const file = new File([blob], ex.file, { type: blob.type || MIME[ext] || 'image/png' })
        const intake = await readSheetFile(file)
        // The intake unmounts on success (the studio takes over), so the busy
        // state only needs resetting on failure.
        setSource(intake.source, intake.image)
      } catch {
        setError('Could not load that sheet. Check your connection and try again.')
        setLoadingFile(null)
      }
    },
    [loadingFile, setSource],
  )

  return (
    <div className="flex flex-col gap-3">
      <div className={`grid gap-3 ${className ?? 'sm:grid-cols-2'}`}>
        {SHEET_EXAMPLES.map((ex) => (
          <ExampleCard
            key={ex.file}
            url={sheetUrl(ex.file)}
            file={ex.file}
            name={ex.name}
            blurb={ex.blurb}
            busy={loadingFile === ex.file}
            disabled={!!loadingFile}
            onClick={() => void pick(ex)}
            fit="cover"
          />
        ))}
      </div>
      {error && <p className="text-xs text-bad">{error}</p>}
    </div>
  )
}
